services:
  grafana-server:
    image: grafana/grafana
    container_name: grafana-server
    restart: unless-stopped
    ports:
      - '3010:3000'
    networks:
      - monitoring-net
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: {}

networks:
  monitoring-net:
    external: true
